=== dotkim/mop-fork/schemas/character.schema.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$ref": "#/definitions/Welcome",
	"definitions": {
		"Welcome": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"classes": {
					"$ref": "#/definitions/Classes"
				},
				"specs": {
					"$ref": "#/definitions/Specs"
				},
				"races": {
					"$ref": "#/definitions/Races"
				},
				"professions": {
					"$ref": "#/definitions/Professions"
				}
			},
			"required": ["classes", "professions", "races", "specs"],
			"title": "Welcome"
		},
		"Classes": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"death_knight": {
					"type": "string"
				},
				"druid": {
					"type": "string"
				},
				"hunter": {
					"type": "string"
				},
				"mage": {
					"type": "string"
				},
				"monk": {
					"type": "string"
				},
				"paladin": {
					"type": "string"
				},
				"priest": {
					"type": "string"
				},
				"rogue": {
					"type": "string"
				},
				"shaman": {
					"type": "string"
				},
				"warlock": {
					"type": "string"
				},
				"warrior": {
					"type": "string"
				}
			},
			"required": ["death_knight", "druid", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
			"title": "Classes"
		},
		"Professions": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"unknown": {
					"type": "string"
				},
				"alchemy": {
					"type": "string"
				},
				"blacksmithing": {
					"type": "string"
				},
				"enchanting": {
					"type": "string"
				},
				"engineering": {
					"type": "string"
				},
				"herbalism": {
					"type": "string"
				},
				"inscription": {
					"type": "string"
				},
				"jewelcrafting": {
					"type": "string"
				},
				"leatherworking": {
					"type": "string"
				},
				"mining": {
					"type": "string"
				},
				"skinning": {
					"type": "string"
				},
				"tailoring": {
					"type": "string"
				},
				"archeology": {
					"type": "string"
				}
			},
			"required": [
				"alchemy",
				"archeology",
				"blacksmithing",
				"enchanting",
				"engineering",
				"herbalism",
				"inscription",
				"jewelcrafting",
				"leatherworking",
				"mining",
				"skinning",
				"tailoring",
				"unknown"
			],
			"title": "Professions"
		},
		"Races": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"unknown": {
					"type": "string"
				},
				"blood_elf": {
					"type": "string"
				},
				"draenei": {
					"type": "string"
				},
				"dwarf": {
					"type": "string"
				},
				"gnome": {
					"type": "string"
				},
				"goblin": {
					"type": "string"
				},
				"human": {
					"type": "string"
				},
				"night_elf": {
					"type": "string"
				},
				"orc": {
					"type": "string"
				},
				"alliance_pandaren": {
					"type": "string"
				},
				"horde_pandaren": {
					"type": "string"
				},
				"tauren": {
					"type": "string"
				},
				"troll": {
					"type": "string"
				},
				"undead": {
					"type": "string"
				},
				"worgen": {
					"type": "string"
				}
			},
			"required": [
				"alliance_pandaren",
				"blood_elf",
				"draenei",
				"dwarf",
				"gnome",
				"goblin",
				"horde_pandaren",
				"human",
				"night_elf",
				"orc",
				"tauren",
				"troll",
				"undead",
				"unknown",
				"worgen"
			],
			"title": "Races"
		},
		"Specs": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"death_knight": {
					"$ref": "#/definitions/DeathKnight"
				},
				"druid": {
					"$ref": "#/definitions/Druid"
				},
				"hunter": {
					"$ref": "#/definitions/Hunter"
				},
				"mage": {
					"$ref": "#/definitions/Mage"
				},
				"monk": {
					"$ref": "#/definitions/Monk"
				},
				"paladin": {
					"$ref": "#/definitions/Paladin"
				},
				"priest": {
					"$ref": "#/definitions/Priest"
				},
				"rogue": {
					"$ref": "#/definitions/Rogue"
				},
				"shaman": {
					"$ref": "#/definitions/Shaman"
				},
				"warlock": {
					"$ref": "#/definitions/Warlock"
				},
				"warrior": {
					"$ref": "#/definitions/Warrior"
				}
			},
			"required": ["death_knight", "druid", "hunter", "mage", "monk", "paladin", "priest", "rogue", "shaman", "warlock", "warrior"],
			"title": "Specs"
		},
		"DeathKnight": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"blood": {
					"type": "string"
				},
				"frost": {
					"type": "string"
				},
				"unholy": {
					"type": "string"
				}
			},
			"required": ["blood", "frost", "unholy"],
			"title": "DeathKnight"
		},
		"Druid": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"balance": {
					"type": "string"
				},
				"feral": {
					"type": "string"
				},
				"guardian": {
					"type": "string"
				},
				"restoration": {
					"type": "string"
				}
			},
			"required": ["balance", "feral", "guardian", "restoration"],
			"title": "Druid"
		},
		"Hunter": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"beast_mastery": {
					"type": "string"
				},
				"marksmanship": {
					"type": "string"
				},
				"survival": {
					"type": "string"
				}
			},
			"required": ["beast_mastery", "marksmanship", "survival"],
			"title": "Hunter"
		},
		"Mage": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"arcane": {
					"type": "string"
				},
				"fire": {
					"type": "string"
				},
				"frost": {
					"type": "string"
				}
			},
			"required": ["arcane", "fire", "frost"],
			"title": "Mage"
		},
		"Monk": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"brewmaster": {
					"type": "string"
				},
				"mistweaver": {
					"type": "string"
				},
				"windwalker": {
					"type": "string"
				}
			},
			"required": ["brewmaster", "mistweaver", "windwalker"],
			"title": "Monk"
		},
		"Paladin": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"holy": {
					"type": "string"
				},
				"protection": {
					"type": "string"
				},
				"retribution": {
					"type": "string"
				}
			},
			"required": ["holy", "protection", "retribution"],
			"title": "Paladin"
		},
		"Priest": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"discipline": {
					"type": "string"
				},
				"holy": {
					"type": "string"
				},
				"shadow": {
					"type": "string"
				}
			},
			"required": ["discipline", "holy", "shadow"],
			"title": "Priest"
		},
		"Rogue": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"assassination": {
					"type": "string"
				},
				"combat": {
					"type": "string"
				},
				"subtlety": {
					"type": "string"
				}
			},
			"required": ["assassination", "combat", "subtlety"],
			"title": "Rogue"
		},
		"Shaman": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"elemental": {
					"type": "string"
				},
				"enhancement": {
					"type": "string"
				},
				"restoration": {
					"type": "string"
				}
			},
			"required": ["elemental", "enhancement", "restoration"],
			"title": "Shaman"
		},
		"Warlock": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"affliction": {
					"type": "string"
				},
				"demonology": {
					"type": "string"
				},
				"destruction": {
					"type": "string"
				}
			},
			"required": ["affliction", "demonology", "destruction"],
			"title": "Warlock"
		},
		"Warrior": {
			"type": "object",
			"additionalProperties": false,
			"properties": {
				"arms": {
					"type": "string"
				},
				"fury": {
					"type": "string"
				},
				"protection": {
					"type": "string"
				}
			},
			"required": ["arms", "fury", "protection"],
			"title": "Warrior"
		}
	}
}

=== dotkim/mop-fork/assets/locales/fr/character.json
{
	"classes": {
		"death_knight": "Chevalier de la mort",
		"druid": "Druide",
		"hunter": "Chasseur",
		"mage": "Mage",
		"monk": "Moine",
		"paladin": "Paladin",
		"priest": "Prêtre",
		"rogue": "Voleur",
		"shaman": "Chaman",
		"warlock": "Démoniste",
		"warrior": "Guerrier"
	},
	"specs": {
		"death_knight": {
			"blood": "Sang",
			"frost": "Givre",
			"unholy": "Impie"
		},
		"druid": {
			"balance": "Équilibre",
			"feral": "Farouche",
			"guardian": "Gardien",
			"restoration": "Restauration"
		},
		"hunter": {
			"beast_mastery": "Maîtrise des bêtes",
			"marksmanship": "Précision",
			"survival": "Survie"
		},
		"mage": {
			"arcane": "Arcane",
			"fire": "Feu",
			"frost": "Givre"
		},
		"monk": {
			"brewmaster": "Maître brasseur",
			"mistweaver": "Tisse-brume",
			"windwalker": "Marche-vent"
		},
		"paladin": {
			"holy": "Sacré",
			"protection": "Protection",
			"retribution": "Vindicte"
		},
		"priest": {
			"discipline": "Discipline",
			"holy": "Sacré",
			"shadow": "Ombre"
		},
		"rogue": {
			"assassination": "Assassinat",
			"combat": "Combat",
			"subtlety": "Finesse"
		},
		"shaman": {
			"elemental": "Élémentaire",
			"enhancement": "Amélioration",
			"restoration": "Restauration"
		},
		"warlock": {
			"affliction": "Affliction",
			"demonology": "Démonologie",
			"destruction": "Destruction"
		},
		"warrior": {
			"arms": "Armes",
			"fury": "Fureur",
			"protection": "Protection"
		}
	},
	"races": {
		"unknown": "Aucun",
		"blood_elf": "Elfe de sang",
		"draenei": "Draenei",
		"dwarf": "Nain",
		"gnome": "Gnome",
		"goblin": "Gobelin",
		"human": "Humain",
		"night_elf": "Elfe de la nuit",
		"orc": "Orc",
		"alliance_pandaren": "Pandaren (A)",
		"horde_pandaren": "Pandaren (H)",
		"tauren": "Tauren",
		"troll": "Troll",
		"undead": "Mort-vivant",
		"worgen": "Worgen"
	},
	"professions": {
		"unknown": "Aucun",
		"alchemy": "Alchimie",
		"blacksmithing": "Forge",
		"enchanting": "Enchantement",
		"engineering": "Ingénierie",
		"herbalism": "Herboristerie",
		"inscription": "Calligraphie",
		"jewelcrafting": "Joaillerie",
		"leatherworking": "Travail du cuir",
		"mining": "Minage",
		"skinning": "Dépeçage",
		"tailoring": "Couture",
		"archeology": "Archéologie"
	}
}
